// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Email           string
	Password        string
	FirstName       sql.NullString
	LastName        sql.NullString
	IsAdministrator bool
	Active          bool
}

type LoginSession struct {
	SessionID string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	LastLogin time.Time
	IpAddr    pqtype.Inet
	UserAgent sql.NullString
	ExpiredAt time.Time
	Csrf      sql.NullString
}

type RolePermission struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Role        string
	Permissions pqtype.NullRawMessage
}

type UserRole struct {
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
